apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: with_ance
spec:
  destination:
    name: ''
    namespace: argo
    server: 'https://kubernetes.default.svc'
  source:
    path: with_ance
    repoURL: 'https://github.com/ysa5347/with_ance_config.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.tag
          value: tag
  sources: []
  project: default