apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ecr-refresher.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ecr-refresher.labels" . | nindent 4 }}