{{ range $index, $tag := .Values.images.tags }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "with_ance.fullname" $ }}-{{ .name }}
  labels:
    {{- include "with_ance.labels" $ | nindent 4 }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "with_ance.selectorLabels" $ | nindent 4 }}-{{ .name }}
{{ end }}


